"""empty message

Revision ID: 83b733265246
Revises: 6940efe9048b
Create Date: 2020-12-15 23:07:49.600312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b733265246'
down_revision = '6940efe9048b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_', sa.Integer(), nullable=False))
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('users', 'id_')
    # ### end Alembic commands ###
