"""empty message

Revision ID: c229071a0ac3
Revises: 
Create Date: 2020-12-28 20:03:17.214417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c229071a0ac3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=250), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('surn', sa.String(length=250), nullable=False),
    sa.Column('card', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
